[project]
name = "service"
version = "0.1.0"
description = "python executor mcp and other services"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.0",
    "fastmcp>=2.13.0.2",
    "jupyter-client>=8.6.3",
    "nbformat>=5.10.4",
    "playwright>=1.55.0",
]
